import { createEnv } from "@t3-oss/env-nextjs";
import z from "zod";

export const env = () =>
  createEnv({
    client: {
      NEXT_PUBLIC_FIREBASE_API_KEY: z.string(),
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: z.string(),
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: z.string(),
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: z.string(),
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: z.string(),
      NEXT_PUBLIC_FIREBASE_APP_ID: z.string(),
    },
    server: {
      FIREBASE_PROJECT_ID: z.string(),
      FIREBASE_CLIENT_EMAIL: z.string(),
      FIREBASE_PRIVATE_KEY: z.string(),
      FIREBASE_STORAGE_BUCKET: z.string(),
    },
    runtimeEnv: {
      NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:
        process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
      NEXT_PUBLIC_FIREBASE_PROJECT_ID:
        process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:
        process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
        process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
      NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
      FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
      FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
      FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
      FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    },
  });
